include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: false
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Sometimes useful to print to console, should look for alternatives for more control over printing
    avoid_print: false

    sort_pub_dependencies: true

    use_to_and_as_if_applicable : true
    unnecessary_null_in_if_null_operators : true
    unnecessary_lambdas : true
    unnecessary_getters_setters : true
    unawaited_futures : true
    type_init_formals : true
    unnecessary_await_in_return : true
    sized_box_for_whitespace : true
    recursive_getters : true
    prefer_spread_collections : true
    prefer_null_aware_operators : true
    prefer_mixin : true
    prefer_is_not_operator : true
    prefer_is_not_empty : true
    prefer_is_empty : true
    prefer_inlined_adds : true
    prefer_generic_function_type_aliases : true
    prefer_function_declarations_over_variables : true
    prefer_if_null_operators : true
    prefer_for_elements_to_map_fromIterable : true
    prefer_equal_for_default_values : true
    prefer_contains : true
    prefer_conditional_assignment : true
    prefer_collection_literals : true
    parameter_assignments : true
    package_prefixed_library_names : true
    package_api_docs : true
    one_member_abstracts : true
    null_closures : true
    non_constant_identifier_names : true
    empty_constructor_bodies : true
    directives_ordering : true
    avoid_void_async : true
    avoid_shadowing_type_parameters : true
    avoid_returning_this : true
    avoid_return_types_on_setters : true
    avoid_null_checks_in_equality_operators : true
    avoid_implementing_value_types : true
    avoid_equals_and_hash_code_on_mutable_classes : true
    always_require_non_null_named_parameters : true
    use_rethrow_when_possible : true
    use_function_type_syntax_for_parameters : true
    use_setters_to_change_properties : true
    avoid_as : true
  
    # Back to the 80s
    lines_longer_than_80_chars: false